name: Publish Release

on:
  workflow_dispatch:
    inputs:
      mod-id:
        description: mod id (without mat.) to release
        required: true
        type: string
      publish:
        description: publish mod to index
        default: true
        type: boolean
      debug:
        description: enable tmate debug
        default: false
        type: boolean

jobs:
  draft:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Define variables
        id: info
        run: |
          # gets the latest action run from the main branch
          BRANCH=main
          API_URL="https://api.github.com/repos/matcool/geode-mods/actions/workflows/build.yml/runs?per_page=1&branch=$BRANCH&event=push&status=success"
          RUN_ID=$(curl $API_URL | jq .workflow_runs[0].id)
          VERSION=$(jq -r .version ${{ inputs.mod-id }}/mod.json)
          # guarantee v prefix
          VERSION=v${VERSION#v}

          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - uses: actions/download-artifact@v4
        with:
          run-id: ${{ steps.info.outputs.run_id }}
          path: ${{ github.workspace }}/artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.mod-id }}-${{ steps.info.outputs.version }}
          files: |
            ./artifacts/Build Output/mat.${{ inputs.mod-id }}.geode

      # fetches latest cli
      - name: Setup CLI
        if: ${{ inputs.publish }}
        uses: geode-sdk/cli/.github/actions/setup@main
      
      - name: Publish to index
        if: ${{ inputs.publish }}
        run: |
          geode index login --token ${{ secrets.GEODE_TOKEN }}
          geode index mods update ${{ fromJSON(steps.create_release.outputs.assets)[0].browser_download_url }}

      - name: Setup tmate session
        if: ${{ !cancelled() && inputs.debug }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true